# Generated by Django 4.2.1 on 2023-05-22 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("app", "0003_alter_answer_author_alter_question_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="question",
            name="rating",
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.profile"
                    ),
                ),
            ],
        ),
    ]
