# Generated by Django 4.2.1 on 2023-05-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_remove_answer_rating_remove_question_rating_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="rating",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
